manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/alescito
  projects:
    - name: zmk-mine 
      remote: alescito
      revision: main
      import: app/west.yml
  self:
    path: config
